$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: info
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "node"
      args:
        [
          "C:\\Users\\kevin\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
          "C:/Users/kevin/ClaudeMCPFolder",
          "H:/temp storage",
          "C:/Users/kevin/OneDrive/Desktop",
        ]

openai:
  # API key is loaded from OPENAI_API_KEY in .env file
  default_model: gpt-4o
